# Generated by Django 5.2.4 on 2026-07-17 12:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatKlasifikasi',
            fields=[
                ('id_riwayat', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_file', models.CharField(max_length=255)),
                ('ukuran_file', models.CharField(max_length=50)),
                ('format_file', models.CharField(max_length=20)),
                ('genre_prediksi', models.CharField(max_length=100)),
                ('genre_icon', models.CharField(default='🎵', max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('waktu_klasifikasi', models.DateTimeField(auto_now_add=True)),
                ('top_features_json', models.TextField(blank=True, default='[]')),
                ('probabilities_json', models.TextField(blank=True, default='[]')),
            ],
            options={
                'verbose_name': 'Riwayat Klasifikasi',
                'verbose_name_plural': 'Riwayat Klasifikasi',
                'db_table': 'tb_riwayat_klasifikasi',
                'ordering': ['-waktu_klasifikasi'],
            },
        ),
        migrations.CreateModel(
            name='FiturAudio',
            fields=[
                ('id_fitur_audio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mfcc_mean', models.FloatField(default=0.0)),
                ('spectral_centroid', models.FloatField(default=0.0)),
                ('zero_crossing_rate', models.FloatField(default=0.0)),
                ('chroma_mean', models.FloatField(default=0.0)),
                ('tempo', models.FloatField(default=0.0)),
                ('id_riwayat', models.OneToOneField(db_column='id_riwayat', on_delete=django.db.models.deletion.CASCADE, related_name='fitur_audio', to='Klasifikasi.riwayatklasifikasi')),
            ],
            options={
                'verbose_name': 'Fitur Audio',
                'verbose_name_plural': 'Fitur Audio',
                'db_table': 'tb_fitur_audio',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Pengguna',
                'verbose_name_plural': 'Pengguna',
                'db_table': 'tb_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id_profile', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('pengelola_studio', 'Pengelola Studio'), ('pengguna_studio', 'Pengguna Studio')], default='pengguna_studio', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Pengguna',
                'verbose_name_plural': 'Profil Pengguna',
                'db_table': 'tb_user_profile',
            },
        ),
        migrations.AddField(
            model_name='riwayatklasifikasi',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id_laporan', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul_laporan', models.CharField(max_length=255)),
                ('periode_awal', models.DateField(blank=True, null=True)),
                ('periode_akhir', models.DateField(blank=True, null=True)),
                ('format_ekspor', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel (XLSX)')], default='pdf', max_length=10)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laporan',
                'verbose_name_plural': 'Laporan',
                'db_table': 'tb_laporan',
                'ordering': ['-tanggal_dibuat'],
            },
        ),
    ]
